use space::{point2, vec2, Point2, Vec2};

#[derive(Debug, Clone)]
pub enum InputEvent {
    CursorMoved(Point2),
    KeyDown(Key),
    KeyUp(Key),
    MouseDown(MouseButton),
    MouseUp(MouseButton),
    MouseWheel(Vec2),
    Unhandled,
}
#[cfg(feature = "winit")]
impl From<winit::event::WindowEvent> for InputEvent {
    fn from(event: winit::event::WindowEvent) -> Self {
        match event {
            winit::event::WindowEvent::CursorMoved { position, .. } => {
                Self::CursorMoved(point2(position.x, position.y))
            }
            winit::event::WindowEvent::MouseWheel { delta, .. } => {
                let delta = match delta {
                    winit::event::MouseScrollDelta::LineDelta(x, y) => vec2(x as f64, y as f64),
                    winit::event::MouseScrollDelta::PixelDelta(winit::dpi::PhysicalPosition {
                        x,
                        y,
                    }) => vec2(x, y),
                };
                Self::MouseWheel(delta)
            }
            winit::event::WindowEvent::MouseInput { state, button, .. } => {
                let evt_button = match button {
                    winit::event::MouseButton::Left => MouseButton::Primary,
                    winit::event::MouseButton::Right => MouseButton::Secondary,
                    winit::event::MouseButton::Middle => MouseButton::Aux,
                    _ => return Self::Unhandled,
                };

                match state.is_pressed() {
                    true => Self::MouseDown(evt_button),
                    false => Self::MouseUp(evt_button),
                }
            }
            winit::event::WindowEvent::KeyboardInput {
                device_id,
                event,
                is_synthetic,
            } => {
                if let winit::keyboard::PhysicalKey::Code(code) = event.physical_key {
                    if let Some(key) = Key::from_keycode(code) {
                        match event.state.is_pressed() {
                            true => Self::KeyDown(key),
                            false => Self::KeyUp(key),
                        }
                    } else {
                        Self::Unhandled
                    }
                } else {
                    Self::Unhandled
                }
            }
            _ => Self::Unhandled,
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum MouseButton {
    // Main mouse button, usually left
    Primary,

    // Secondary mouse button, usually left
    Secondary,

    // Auxiliary mouse button, usually middle or mousewheel button
    Aux,
}

#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub enum Key {
    Backquote,
    Backslash,
    BracketLeft,
    BracketRight,
    Comma,
    Digit0,
    Digit1,
    Digit2,
    Digit3,
    Digit4,
    Digit5,
    Digit6,
    Digit7,
    Digit8,
    Digit9,
    Equal,
    IntlBackslash,
    IntlRo,
    IntlYen,
    KeyA,
    KeyB,
    KeyC,
    KeyD,
    KeyE,
    KeyF,
    KeyG,
    KeyH,
    KeyI,
    KeyJ,
    KeyK,
    KeyL,
    KeyM,
    KeyN,
    KeyO,
    KeyP,
    KeyQ,
    KeyR,
    KeyS,
    KeyT,
    KeyU,
    KeyV,
    KeyW,
    KeyX,
    KeyY,
    KeyZ,
    Minus,
    Period,
    Quote,
    Semicolon,
    Slash,
    AltLeft,
    AltRight,
    Backspace,
    CapsLock,
    ContextMenu,
    ControlLeft,
    ControlRight,
    Enter,
    SuperLeft,
    SuperRight,
    ShiftLeft,
    ShiftRight,
    Space,
    Tab,
    Convert,
    KanaMode,
    Lang1,
    Lang2,
    Lang3,
    Lang4,
    Lang5,
    NonConvert,
    Delete,
    End,
    Help,
    Home,
    Insert,
    PageDown,
    PageUp,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    NumLock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadAdd,
    NumpadBackspace,
    NumpadClear,
    NumpadClearEntry,
    NumpadComma,
    NumpadDecimal,
    NumpadDivide,
    NumpadEnter,
    NumpadEqual,
    NumpadHash,
    NumpadMemoryAdd,
    NumpadMemoryClear,
    NumpadMemoryRecall,
    NumpadMemoryStore,
    NumpadMemorySubtract,
    NumpadMultiply,
    NumpadParenLeft,
    NumpadParenRight,
    NumpadStar,
    NumpadSubtract,
    Escape,
    Fn,
    FnLock,
    PrintScreen,
    ScrollLock,
    Pause,
    BrowserBack,
    BrowserFavorites,
    BrowserForward,
    BrowserHome,
    BrowserRefresh,
    BrowserSearch,
    BrowserStop,
    Eject,
    LaunchApp1,
    LaunchApp2,
    LaunchMail,
    MediaPlayPause,
    MediaSelect,
    MediaStop,
    MediaTrackNext,
    MediaTrackPrevious,
    Power,
    Sleep,
    AudioVolumeDown,
    AudioVolumeMute,
    AudioVolumeUp,
    WakeUp,
    Meta,
    Hyper,
    Turbo,
    Abort,
    Resume,
    Suspend,
    Again,
    Copy,
    Cut,
    Find,
    Open,
    Paste,
    Props,
    Select,
    Undo,
    Hiragana,
    Katakana,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    F25,
    F26,
    F27,
    F28,
    F29,
    F30,
    F31,
    F32,
    F33,
    F34,
    F35,
}
impl Key {
    pub fn is_control(&self) -> bool {
        *self == Self::ControlLeft || *self == Self::ControlRight
    }

    pub fn is_shift(&self) -> bool {
        *self == Self::ShiftLeft || *self == Self::ShiftRight
    }

    pub fn is_alt(&self) -> bool {
        *self == Self::AltLeft || *self == Self::AltRight
    }

    #[cfg(feature = "winit")]
    fn from_keycode(keycode: winit::keyboard::KeyCode) -> Option<Self> {
        match keycode {
            winit::keyboard::KeyCode::Backquote => Some(Self::Backquote),
            winit::keyboard::KeyCode::Backslash => Some(Self::Backslash),
            winit::keyboard::KeyCode::BracketLeft => Some(Self::BracketLeft),
            winit::keyboard::KeyCode::BracketRight => Some(Self::BracketRight),
            winit::keyboard::KeyCode::Comma => Some(Self::Comma),
            winit::keyboard::KeyCode::Digit0 => Some(Self::Digit0),
            winit::keyboard::KeyCode::Digit1 => Some(Self::Digit1),
            winit::keyboard::KeyCode::Digit2 => Some(Self::Digit2),
            winit::keyboard::KeyCode::Digit3 => Some(Self::Digit3),
            winit::keyboard::KeyCode::Digit4 => Some(Self::Digit4),
            winit::keyboard::KeyCode::Digit5 => Some(Self::Digit5),
            winit::keyboard::KeyCode::Digit6 => Some(Self::Digit6),
            winit::keyboard::KeyCode::Digit7 => Some(Self::Digit7),
            winit::keyboard::KeyCode::Digit8 => Some(Self::Digit8),
            winit::keyboard::KeyCode::Digit9 => Some(Self::Digit9),
            winit::keyboard::KeyCode::Equal => Some(Self::Equal),
            winit::keyboard::KeyCode::IntlBackslash => Some(Self::IntlBackslash),
            winit::keyboard::KeyCode::IntlRo => Some(Self::IntlRo),
            winit::keyboard::KeyCode::IntlYen => Some(Self::IntlYen),
            winit::keyboard::KeyCode::KeyA => Some(Self::KeyA),
            winit::keyboard::KeyCode::KeyB => Some(Self::KeyB),
            winit::keyboard::KeyCode::KeyC => Some(Self::KeyC),
            winit::keyboard::KeyCode::KeyD => Some(Self::KeyD),
            winit::keyboard::KeyCode::KeyE => Some(Self::KeyE),
            winit::keyboard::KeyCode::KeyF => Some(Self::KeyF),
            winit::keyboard::KeyCode::KeyG => Some(Self::KeyG),
            winit::keyboard::KeyCode::KeyH => Some(Self::KeyH),
            winit::keyboard::KeyCode::KeyI => Some(Self::KeyI),
            winit::keyboard::KeyCode::KeyJ => Some(Self::KeyJ),
            winit::keyboard::KeyCode::KeyK => Some(Self::KeyK),
            winit::keyboard::KeyCode::KeyL => Some(Self::KeyL),
            winit::keyboard::KeyCode::KeyM => Some(Self::KeyM),
            winit::keyboard::KeyCode::KeyN => Some(Self::KeyN),
            winit::keyboard::KeyCode::KeyO => Some(Self::KeyO),
            winit::keyboard::KeyCode::KeyP => Some(Self::KeyP),
            winit::keyboard::KeyCode::KeyQ => Some(Self::KeyQ),
            winit::keyboard::KeyCode::KeyR => Some(Self::KeyR),
            winit::keyboard::KeyCode::KeyS => Some(Self::KeyS),
            winit::keyboard::KeyCode::KeyT => Some(Self::KeyT),
            winit::keyboard::KeyCode::KeyU => Some(Self::KeyU),
            winit::keyboard::KeyCode::KeyV => Some(Self::KeyV),
            winit::keyboard::KeyCode::KeyW => Some(Self::KeyW),
            winit::keyboard::KeyCode::KeyX => Some(Self::KeyX),
            winit::keyboard::KeyCode::KeyY => Some(Self::KeyY),
            winit::keyboard::KeyCode::KeyZ => Some(Self::KeyZ),
            winit::keyboard::KeyCode::Minus => Some(Self::Minus),
            winit::keyboard::KeyCode::Period => Some(Self::Period),
            winit::keyboard::KeyCode::Quote => Some(Self::Quote),
            winit::keyboard::KeyCode::Semicolon => Some(Self::Semicolon),
            winit::keyboard::KeyCode::Slash => Some(Self::Slash),
            winit::keyboard::KeyCode::AltLeft => Some(Self::AltLeft),
            winit::keyboard::KeyCode::AltRight => Some(Self::AltRight),
            winit::keyboard::KeyCode::Backspace => Some(Self::Backspace),
            winit::keyboard::KeyCode::CapsLock => Some(Self::CapsLock),
            winit::keyboard::KeyCode::ContextMenu => Some(Self::ContextMenu),
            winit::keyboard::KeyCode::ControlLeft => Some(Self::ControlLeft),
            winit::keyboard::KeyCode::ControlRight => Some(Self::ControlRight),
            winit::keyboard::KeyCode::Enter => Some(Self::Enter),
            winit::keyboard::KeyCode::SuperLeft => Some(Self::SuperLeft),
            winit::keyboard::KeyCode::SuperRight => Some(Self::SuperRight),
            winit::keyboard::KeyCode::ShiftLeft => Some(Self::ShiftLeft),
            winit::keyboard::KeyCode::ShiftRight => Some(Self::ShiftRight),
            winit::keyboard::KeyCode::Space => Some(Self::Space),
            winit::keyboard::KeyCode::Tab => Some(Self::Tab),
            winit::keyboard::KeyCode::Convert => Some(Self::Convert),
            winit::keyboard::KeyCode::KanaMode => Some(Self::KanaMode),
            winit::keyboard::KeyCode::Lang1 => Some(Self::Lang1),
            winit::keyboard::KeyCode::Lang2 => Some(Self::Lang2),
            winit::keyboard::KeyCode::Lang3 => Some(Self::Lang3),
            winit::keyboard::KeyCode::Lang4 => Some(Self::Lang4),
            winit::keyboard::KeyCode::Lang5 => Some(Self::Lang5),
            winit::keyboard::KeyCode::NonConvert => Some(Self::NonConvert),
            winit::keyboard::KeyCode::Delete => Some(Self::Delete),
            winit::keyboard::KeyCode::End => Some(Self::End),
            winit::keyboard::KeyCode::Help => Some(Self::Help),
            winit::keyboard::KeyCode::Home => Some(Self::Home),
            winit::keyboard::KeyCode::Insert => Some(Self::Insert),
            winit::keyboard::KeyCode::PageDown => Some(Self::PageDown),
            winit::keyboard::KeyCode::PageUp => Some(Self::PageUp),
            winit::keyboard::KeyCode::ArrowDown => Some(Self::ArrowDown),
            winit::keyboard::KeyCode::ArrowLeft => Some(Self::ArrowLeft),
            winit::keyboard::KeyCode::ArrowRight => Some(Self::ArrowRight),
            winit::keyboard::KeyCode::ArrowUp => Some(Self::ArrowUp),
            winit::keyboard::KeyCode::NumLock => Some(Self::NumLock),
            winit::keyboard::KeyCode::Numpad0 => Some(Self::Numpad0),
            winit::keyboard::KeyCode::Numpad1 => Some(Self::Numpad1),
            winit::keyboard::KeyCode::Numpad2 => Some(Self::Numpad2),
            winit::keyboard::KeyCode::Numpad3 => Some(Self::Numpad3),
            winit::keyboard::KeyCode::Numpad4 => Some(Self::Numpad4),
            winit::keyboard::KeyCode::Numpad5 => Some(Self::Numpad5),
            winit::keyboard::KeyCode::Numpad6 => Some(Self::Numpad6),
            winit::keyboard::KeyCode::Numpad7 => Some(Self::Numpad7),
            winit::keyboard::KeyCode::Numpad8 => Some(Self::Numpad8),
            winit::keyboard::KeyCode::Numpad9 => Some(Self::Numpad9),
            winit::keyboard::KeyCode::NumpadAdd => Some(Self::NumpadAdd),
            winit::keyboard::KeyCode::NumpadBackspace => Some(Self::NumpadBackspace),
            winit::keyboard::KeyCode::NumpadClear => Some(Self::NumpadClear),
            winit::keyboard::KeyCode::NumpadClearEntry => Some(Self::NumpadClearEntry),
            winit::keyboard::KeyCode::NumpadComma => Some(Self::NumpadComma),
            winit::keyboard::KeyCode::NumpadDecimal => Some(Self::NumpadDecimal),
            winit::keyboard::KeyCode::NumpadDivide => Some(Self::NumpadDivide),
            winit::keyboard::KeyCode::NumpadEnter => Some(Self::NumpadEnter),
            winit::keyboard::KeyCode::NumpadEqual => Some(Self::NumpadEqual),
            winit::keyboard::KeyCode::NumpadHash => Some(Self::NumpadHash),
            winit::keyboard::KeyCode::NumpadMemoryAdd => Some(Self::NumpadMemoryAdd),
            winit::keyboard::KeyCode::NumpadMemoryClear => Some(Self::NumpadMemoryClear),
            winit::keyboard::KeyCode::NumpadMemoryRecall => Some(Self::NumpadMemoryRecall),
            winit::keyboard::KeyCode::NumpadMemoryStore => Some(Self::NumpadMemoryStore),
            winit::keyboard::KeyCode::NumpadMemorySubtract => Some(Self::NumpadMemorySubtract),
            winit::keyboard::KeyCode::NumpadMultiply => Some(Self::NumpadMultiply),
            winit::keyboard::KeyCode::NumpadParenLeft => Some(Self::NumpadParenLeft),
            winit::keyboard::KeyCode::NumpadParenRight => Some(Self::NumpadParenRight),
            winit::keyboard::KeyCode::NumpadStar => Some(Self::NumpadStar),
            winit::keyboard::KeyCode::NumpadSubtract => Some(Self::NumpadSubtract),
            winit::keyboard::KeyCode::Escape => Some(Self::Escape),
            winit::keyboard::KeyCode::Fn => Some(Self::Fn),
            winit::keyboard::KeyCode::FnLock => Some(Self::FnLock),
            winit::keyboard::KeyCode::PrintScreen => Some(Self::PrintScreen),
            winit::keyboard::KeyCode::ScrollLock => Some(Self::ScrollLock),
            winit::keyboard::KeyCode::Pause => Some(Self::Pause),
            winit::keyboard::KeyCode::BrowserBack => Some(Self::BrowserBack),
            winit::keyboard::KeyCode::BrowserFavorites => Some(Self::BrowserFavorites),
            winit::keyboard::KeyCode::BrowserForward => Some(Self::BrowserForward),
            winit::keyboard::KeyCode::BrowserHome => Some(Self::BrowserHome),
            winit::keyboard::KeyCode::BrowserRefresh => Some(Self::BrowserRefresh),
            winit::keyboard::KeyCode::BrowserSearch => Some(Self::BrowserSearch),
            winit::keyboard::KeyCode::BrowserStop => Some(Self::BrowserStop),
            winit::keyboard::KeyCode::Eject => Some(Self::Eject),
            winit::keyboard::KeyCode::LaunchApp1 => Some(Self::LaunchApp1),
            winit::keyboard::KeyCode::LaunchApp2 => Some(Self::LaunchApp2),
            winit::keyboard::KeyCode::LaunchMail => Some(Self::LaunchMail),
            winit::keyboard::KeyCode::MediaPlayPause => Some(Self::MediaPlayPause),
            winit::keyboard::KeyCode::MediaSelect => Some(Self::MediaSelect),
            winit::keyboard::KeyCode::MediaStop => Some(Self::MediaStop),
            winit::keyboard::KeyCode::MediaTrackNext => Some(Self::MediaTrackNext),
            winit::keyboard::KeyCode::MediaTrackPrevious => Some(Self::MediaTrackPrevious),
            winit::keyboard::KeyCode::Power => Some(Self::Power),
            winit::keyboard::KeyCode::Sleep => Some(Self::Sleep),
            winit::keyboard::KeyCode::AudioVolumeDown => Some(Self::AudioVolumeDown),
            winit::keyboard::KeyCode::AudioVolumeMute => Some(Self::AudioVolumeMute),
            winit::keyboard::KeyCode::AudioVolumeUp => Some(Self::AudioVolumeUp),
            winit::keyboard::KeyCode::WakeUp => Some(Self::WakeUp),
            winit::keyboard::KeyCode::Meta => Some(Self::Meta),
            winit::keyboard::KeyCode::Hyper => Some(Self::Hyper),
            winit::keyboard::KeyCode::Turbo => Some(Self::Turbo),
            winit::keyboard::KeyCode::Abort => Some(Self::Abort),
            winit::keyboard::KeyCode::Resume => Some(Self::Resume),
            winit::keyboard::KeyCode::Suspend => Some(Self::Suspend),
            winit::keyboard::KeyCode::Again => Some(Self::Again),
            winit::keyboard::KeyCode::Copy => Some(Self::Copy),
            winit::keyboard::KeyCode::Cut => Some(Self::Cut),
            winit::keyboard::KeyCode::Find => Some(Self::Find),
            winit::keyboard::KeyCode::Open => Some(Self::Open),
            winit::keyboard::KeyCode::Paste => Some(Self::Paste),
            winit::keyboard::KeyCode::Props => Some(Self::Props),
            winit::keyboard::KeyCode::Select => Some(Self::Select),
            winit::keyboard::KeyCode::Undo => Some(Self::Undo),
            winit::keyboard::KeyCode::Hiragana => Some(Self::Hiragana),
            winit::keyboard::KeyCode::Katakana => Some(Self::Katakana),
            winit::keyboard::KeyCode::F1 => Some(Self::F1),
            winit::keyboard::KeyCode::F2 => Some(Self::F2),
            winit::keyboard::KeyCode::F3 => Some(Self::F3),
            winit::keyboard::KeyCode::F4 => Some(Self::F4),
            winit::keyboard::KeyCode::F5 => Some(Self::F5),
            winit::keyboard::KeyCode::F6 => Some(Self::F6),
            winit::keyboard::KeyCode::F7 => Some(Self::F7),
            winit::keyboard::KeyCode::F8 => Some(Self::F8),
            winit::keyboard::KeyCode::F9 => Some(Self::F9),
            winit::keyboard::KeyCode::F10 => Some(Self::F10),
            winit::keyboard::KeyCode::F11 => Some(Self::F11),
            winit::keyboard::KeyCode::F12 => Some(Self::F12),
            winit::keyboard::KeyCode::F13 => Some(Self::F13),
            winit::keyboard::KeyCode::F14 => Some(Self::F14),
            winit::keyboard::KeyCode::F15 => Some(Self::F15),
            winit::keyboard::KeyCode::F16 => Some(Self::F16),
            winit::keyboard::KeyCode::F17 => Some(Self::F17),
            winit::keyboard::KeyCode::F18 => Some(Self::F18),
            winit::keyboard::KeyCode::F19 => Some(Self::F19),
            winit::keyboard::KeyCode::F20 => Some(Self::F20),
            winit::keyboard::KeyCode::F21 => Some(Self::F21),
            winit::keyboard::KeyCode::F22 => Some(Self::F22),
            winit::keyboard::KeyCode::F23 => Some(Self::F23),
            winit::keyboard::KeyCode::F24 => Some(Self::F24),
            winit::keyboard::KeyCode::F25 => Some(Self::F25),
            winit::keyboard::KeyCode::F26 => Some(Self::F26),
            winit::keyboard::KeyCode::F27 => Some(Self::F27),
            winit::keyboard::KeyCode::F28 => Some(Self::F28),
            winit::keyboard::KeyCode::F29 => Some(Self::F29),
            winit::keyboard::KeyCode::F30 => Some(Self::F30),
            winit::keyboard::KeyCode::F31 => Some(Self::F31),
            winit::keyboard::KeyCode::F32 => Some(Self::F32),
            winit::keyboard::KeyCode::F33 => Some(Self::F33),
            winit::keyboard::KeyCode::F34 => Some(Self::F34),
            winit::keyboard::KeyCode::F35 => Some(Self::F35),
            _ => None,
        }
    }
}
