[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
render = { path = "../render" }
dioxus = "0.4.0"
dioxus-web = "0.4.0"
dioxus-logger = "0.4.1"
log = "0.4.20"
gloo = "0.10.0"
wasm-bindgen = "0.2.87"
futures = "0.3.29"
tokio = { version = "1.33.0", features = ["time"] }
async-channel = "2.0.0"
web-sys = { version = "0.3.64", features = [
    "Window",
    "Document",
    "MouseEvent",
    "MouseEventInit",
    "DragEvent",
    "DragEventInit",
    "PointerEvent",
    "Event",
    "EventTarget",
    "EventListener",
    "HtmlCanvasElement",
    "WebGl2RenderingContext",
    "ResizeObserver",
    "ResizeObserverEntry",
] }
js-sys = { version = "0.3.64" }
wgpu = { version = "0.18.0", features = ["webgl"] }
