[package]
name = "viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
render = { path = "../render", features = ["winit"] }
winit = "0.29.3"
env_logger = "0.10"
log = "0.4"
raw-window-handle = "0.6.0"
pollster = "0.3"

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2"
glob = "0.3"
